version: '3.7'
# слева локальная машина , справа папка в контейнере
# файл depends_on говорит о том, что web будет запущен после сервиса(db)
services:
  web:
    build: ./
    container_name: sound_cloud_web
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: sound_cloud_db
    volumes:
      - audio_library_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    container_name: sound_cloud_nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - web

volumes:
  audio_library_postgres_data: